using System.Text;
using Microsoft.CodeAnalysis;

namespace AStar.Dev.Source.Generators.StrongIdCodeGeneration;

internal static class StrongIdCodeGenerator
{
    private const string AutoGeneratedComment = "// <auto-generated/>";

    public static string Generate(StrongIdModel model)
    {
        var ns = model.Namespace is null ? string.Empty : $"namespace {model.Namespace};";
        var accessibility = model.Accessibility == Accessibility.Internal ? "internal" : "public";
        var underlying = GetRequiredUnderlyingIdType(model);
        return GenerateCode(model, ns, accessibility, underlying);
    }

    private static string GenerateCode(StrongIdModel model, string ns, string accessibility, string underlying)
        => new StringBuilder()
            .AppendLine(AutoGeneratedComment)
            .AppendLine()
            .AppendLine("using System;")
            .AppendLine("using System.Collections.Generic;")
            .AppendLine()
            .AppendLine(string.IsNullOrEmpty(ns) ? string.Empty : ns)
            .AppendLine()
            .AppendLine($"{accessibility} readonly partial record struct {model.ModelName}({underlying} Value);")
            .AppendLine().ToString();

    private static string GetRequiredUnderlyingIdType(StrongIdModel model)
    {
        var underlying = model.UnderlyingTypeDisplay;
        if(string.IsNullOrEmpty(underlying))
            return "System.Guid";

        if(underlying.IndexOf('.') < 0)
        {
            if(underlying == "Guid")
                underlying = "System.Guid";
            else if(underlying == "string")
                underlying = "System.String";
            else if(underlying == "int")
                underlying = "System.Int32";
        }

        return underlying;
    }
}
